# utils/session_manager.py

"""
session_manager.py

This module stores all in-memory recording sessions for EchoGuard.
It keeps track of:
- which 5-second clips belong to which recording session,
- the model results for each clip,
- whether the recording session has finished.

"""

# -------------------------------------------
# GLOBAL IN-MEMORY DICTIONARY
# -------------------------------------------

# Example structure:
# {
#   "1731278402336": {
#       "clips": [
#           {"index": 0, "prediction": "shatter", "confidence": 72.4},
#           {"index": 1, "prediction": "explosion", "confidence": 89.3},
#       ],
#       "finished": False
#   }
# }

session_recordings = {}


def add_clip_result(recording_id, clip_index, prediction, confidence, is_last_clip=False):
    """
    Store a single 5-second clip's prediction result in memory.

    Parameters:
    - recording_id (str): Unique ID generated by frontend for entire recording session
    - clip_index (int): Order of this clip (0, 1, 2, ...)
    - prediction (str OR dict/list): model output for this clip
    - confidence (float OR dict/list): confidence score(s)
    - is_last_clip (bool): Whether this clip is the final one in the session

    Adds the result to session_recordings and marks session as finished if needed.
    """

    # 1. Initialize the session if it doesn't exist yet
    if recording_id not in session_recordings:
        session_recordings[recording_id] = {
            "clips": [],
            "finished": False
        }

    # 2. Append this clip's results
    session_recordings[recording_id]["clips"].append({
        "index": clip_index,
        "prediction": prediction,
        "confidence": confidence
    })

    # 3. If this was the last clip, mark the session as complete
    if is_last_clip:
        session_recordings[recording_id]["finished"] = True

    # 4. Debug print (optional but very helpful)
    print(
        f"[SessionManager] Stored clip {clip_index} for recording {recording_id} | "
        f"prediction={prediction}, confidence={confidence}, last={is_last_clip}"
    )


def finish_session(recording_id):
    """
    Marks a session as finished even if no last-clip flag was provided.
    """
    if recording_id in session_recordings:
        session_recordings[recording_id]["finished"] = True
        print(f"[SessionManager] Session {recording_id} marked as finished.")
    else:
        print(f"[SessionManager] Tried to finish unknown session {recording_id}.")


def get_session(recording_id):
    """
    Returns the entire session dictionary for the given recording_id.
    Returns None if not found.
    """
    return session_recordings.get(recording_id)


def get_all_sessions():
    """Return all stored sessions (for debugging)."""
    return session_recordings
